[project]
name = "takollama"
version = "0.1.0"
description = "RAG library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=1.0.17",
    "langchain-community>=0.3.27",
    "ollama>=0.5.3",
    "pypdf>=6.0.0",
]
